animations = {
  ['attack'] = {
    ['body'] = -0.125*math.pi,
    ['belly'] = nil,
    ['head'] = nil,
    ['arm'] = -0.25*math.pi,
    ['leg'] = 0.875*math.pi,
    ['wing'] = nil,
    ['tail'] = nil,
    ['eye'] = nil,
    ['ear'] = nil,
    ['mouth'] = nil,
    ['hand'] = nil,
    ['feet'] = nil,
    ['snout'] = nil,
    ['pupil'] = nil,
    ['claw'] = nil,
  },
  ['defend'] = {
    ['body'] = 0.125*math.pi,
    ['belly'] = nil,
    ['head'] = 0.125*math.pi,
    ['arm'] = -0.125*math.pi,
    ['leg'] = 1.375*math.pi,
    ['wing'] = nil,
    ['tail'] = nil,
    ['eye'] = nil,
    ['ear'] = nil,
    ['mouth'] = nil,
    ['hand'] = nil,
    ['feet'] = nil,
    ['snout'] = nil,
    ['pupil'] = nil,
    ['claw'] = nil,
    },
  
  }